schema_version = "1.0.0"

id = "pawst_its"
version = "2.2.0"
name = "Pawst-Its"
tagline = "Cat-themed Pawst-Its for every node editor"
maintainer = "Brandon Gutowski"
type = "add-on"

tags = ["Node", "User Interface"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
